### ISSUE TITLE
SMHC: error 0x100 status 0x0

### ISSUE THREAD

**Issue by vvpnet** [szemzoa/awboot#22]
Good afternoon. I constantly face such a problem:
_[I] AWBoot r6160 starting... 
[I] SMHC: sdhci0 controller v50310 initialized 
[W] SMHC: error 0x100 status 0x0 
[W] SMHC: cmd timeout 
[W] SMHC: error 0x100 status 0x0 
[W] SMHC: cmd timeout 
[W] SMHC: init failed, trying SPI_
A successful launch from SD occurs from 3~6 attempts.
I have tried different SD. I have tried different boards(T113-S3). There is such a mistake everywhere.
Tell me what could be the problem?

**Comment by tipstrying** [comment]
I have encountered the same problem. Have you made any new discoveries?

**Comment by vvpnet** [comment]
No. I think I need to use a different loader.

**Comment by olegk0** [comment]
this problem was solved by increasing attempts to initialize MMC

changed sdmmc_init in file sdmmc.c as below
```
int sdmmc_init(sdmmc_pdata_t *data, sdhci_t *hci) {
    data->hci = hci;
    data->online = FALSE;
    int retries = 10;

    do {
        if (sdmmc_detect(data->hci, &data->card) == TRUE) {
            info("SHMC: %s card detected\r\n", data->card.version & SD_VERSION_SD ? "SD" : "MMC");
            return 0;
        }
        mdelay(100);
    } while (retries--);

    return -1;
}
```

**Comment by fpoussin** [comment]
@olegk0 feel free to open a PR so we can merge this improvement 😄
