### ISSUE TITLE
Cannot get kernel to boot, known good kconfig available?

### ISSUE THREAD

**Issue by dave4445** [szemzoa/awboot#31]
I cannot seem to get linux to get through init sequence on my T113-s3 based board.

I'm using:

https://github.com/szemzoa/awboot @ 65c67dde704145faf7da75542b63c0eee4f1ad60

https://github.com/smaeul/linux.git @ b466df90d48fb7ef03f331e0c73c8012ac03a12e

patches from awboot/linux/*patch applied to kernel above.

linux dts/dtsi are sourced from awboot/linux, the dtsi is taken as is, and I modified sun8i-t113-mangopi-dual.dts into onto my own board, nothing major.

None of my devices (uart, spi, mmc, emac, leds, etc..) as defined in my dts get initialized.  It seems like something fundamental is wrong as not even pinctrl is getting setup.

for example:

awboot/linux-6.0-bootlog.txt has:
[    0.935200] sun20i-d1-pinctrl 2000000.pinctrl: initialized sunXi PIO driver
[    0.964674] 2500400.serial: ttyS1 at MMIO 0x2500400 (irq = 231, base_baud = 1500000) is a 16550A
[    0.996144] 2501400.serial: ttyS5 at MMIO 0x2501400 (irq = 232, base_baud = 1500000) is a 16550A

but none of those appear when I booting.  Yes, CONFIG_PINCTRL_SUN20I_D1 and CONFIG_SERIAL_8250_DW etc.. are on.

What's missing from the awboot/linux directory is a defconfig, I've had to guess.

Everything seems to be defered:
```
[   10.719000] sun6i-dma 3002000.dma-controller: No clock specified
[   10.728000] platform 2000000.pinctrl: deferred probe pending
[   10.734000] platform 5000000.clock-controller: deferred probe pending
[   10.740000] platform 3002000.dma-controller: deferred probe pending
[   10.747000] platform 2500800.serial: deferred probe pending
[   10.752000] platform 2500c00.serial: deferred probe pending
[   10.758000] platform 2501000.serial: deferred probe pending
[   10.764000] platform 2501400.serial: deferred probe pending
[   10.770000] platform 4500000.ethernet: deferred probe pending
[   10.775000] platform 7090000.rtc: deferred probe pending
[   10.781000] platform 2502400.i2c: deferred probe pending
[   10.786000] platform pps-in-pins: deferred probe pending
[   10.792000] platform pps-gps-pins: deferred probe pending
[   10.797000] platform 20500a0.watchdog: deferred probe pending
[   10.803000] platform gpio-leds: deferred probe pending
[   10.808000] platform 3040000.crypto: deferred probe pending
[   10.814000] platform 4020000.mmc: deferred probe pending
[   10.820000] platform 3005000.hwlock: deferred probe pending
```

**Comment by szemzoa** [comment]
Hi,

Those patches are not relevant any more, as the T113-S3 support has been upstreamed, so please use recent upstream kernel.

**Comment by dave4445** [comment]
So I found the issue I was seeing.  kconfig didn't have CONFIG_SUN20I_D1_CCU or CONFIG_SUN20I_D1_R_CCU enabled so all devices dependent on clocks of any kind were deferred indefinantly.  Might be nice to add have a reference defconfig.
