### ISSUE TITLE
uart0 console didn't show any message

### ISSUE THREAD

**Issue by actionmask** [szemzoa/awboot#36]
I try to using uart0 as console but I found that there is nothing out from console.
In board.c 
sunxi_usart_t usart0_dbg = {
    .base    = 0x02500000,
    .id      = 0,
    .gpio_tx = {GPIO_PIN(PORTE, 2), GPIO_PERIPH_MUX7},
    .gpio_rx = {GPIO_PIN(PORTE, 3), GPIO_PERIPH_MUX7},
};

in t113 datasheet ,uart0 is Function 6
![圖片](https://github.com/szemzoa/awboot/assets/1112035/b897b775-e132-4dc4-a388-84ab5b7f665b)

I fix to MUX6 and uart0 works.

diff --git a/board.c b/board.c
index 8d4a817..5bd91d1 100644
--- a/board.c
+++ b/board.c
@@ -16,8 +16,8 @@ sunxi_usart_t usart5_dbg = {
 sunxi_usart_t usart0_dbg = {
        .base    = 0x02500000,
        .id              = 0,
-       .gpio_tx = {GPIO_PIN(PORTE, 2), GPIO_PERIPH_MUX7},
-       .gpio_rx = {GPIO_PIN(PORTE, 3), GPIO_PERIPH_MUX7},
+       .gpio_tx = {GPIO_PIN(PORTE, 2), GPIO_PERIPH_MUX6},
+       .gpio_rx = {GPIO_PIN(PORTE, 3), GPIO_PERIPH_MUX6},
 };

 sunxi_usart_t usart3_dbg = {
@@ -57,6 +57,8 @@ sdhci_t sdhci0 = {

 static gpio_t led_blue = GPIO_PIN(PORTD, 22);

**Comment by szemzoa** [comment]
Applied, thanks!
